<?php
namespace ZohoBooksAL\Tests\Metadata;
use ZohoBooksAL\Metadata\Collector\CollectorInterface;
use ZohoBooksAL\Metadata\MetadataCollection;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-23 at 21:53:10.
 */
class MetadataCollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CollectorInterface
     */
    protected $collectorMock;

    /**
     * @var MetadataCollection
     */
    protected $metadataCollection;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->collectorMock = \Mockery::mock('ZohoBooksAL\Metadata\Collector\CollectorInterface');
        $this->metadataCollection = new MetadataCollection($this->collectorMock);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ZohoBooksAL\Metadata\MetadataCollection::getClassMetadata
     * @todo   Implement testGetClassMetadata().
     */
    public function testGetClassMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
